### ISSUE TITLE
Error thrown during packaging 

### ISSUE THREAD

**Issue by ronkorving** [serverless/serverless-python-requirements#657]
I'm seeing the following error since upgrading this plugin from 5.2.0 to 5.2.1.

```
Serverless: Using download cache directory /Users/ronkorving/Library/Caches/serverless-python-requirements/downloadCacheslspyc

 Type Error ----------------------------------------------

  TypeError: ps.stdoutBuffer.trim is not a function
      at getDockerUid (/Users/ronkorving/Projects/myproject/node_modules/serverless-python-requirements/lib/docker.js:200:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async installRequirements (/Users/ronkorving/Projects/myproject/node_modules/serverless-python-requirements/lib/pip.js:341:30)
      at async installRequirementsIfNeeded (/Users/ronkorving/Projects/myproject/node_modules/serverless-python-requirements/lib/pip.js:682:3)
      at async ServerlessPythonRequirements.installAllRequirements (/Users/ronkorving/Projects/myproject/node_modules/serverless-python-requirements/lib/pip.js:760:29)
```

Debug output from Serverless:

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.13.0
     Framework Version:         2.68.0 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

This problem does not occur on 5.2.0.

**Comment by pgrzesik** [comment]
It will be addressed by https://github.com/serverless/serverless-python-requirements/pull/656

**Comment by ronkorving** [comment]
@pgrzesik No worries, thanks for the quick response and care 👍

**Comment by ronkorving** [comment]
Can confirm that the problem has gone away 👍

**Comment by pgrzesik** [comment]
Thanks for confirmation @ronkorving 👍
